refactoring of harvest shell script
several improvements to code, scoping and some speed

diff --git a/harvest b/harvest
--- a/harvest
+++ b/harvest
@@ -308,57 +308,6 @@ function zuper.exit zshexit() { endgame EXIT; return $? }
 
 # }}} Debugging
 
-# {{{ Tempfiles
-
-##########################
-# Temp file handling
-
-vars+=(ztmpfile)
-# ztmp() fills in $ztmpfile global. Caller must copy that variable as
-# it will be overwritten at every call.
-ztmp() {
-    fn ztmp
-
-    ztmpfile=`mktemp`
-    tmpfiles+=($ztmpfile)
-}
-
-vars+=(ztmpdir)
-# ztmpd() fills in $ztmpdir global. Caller must copy that variable as
-# it will be overwritten at every call.
-
-ztmpd() {
-    fn ztmpd
-
-    ztmpdir=`mktemp -d`
-    tmpdirs+=($ztmpdir)
-}
-
-# All tempfiles are freed in endgame()
-_ztmp_destructor() {
-    fn _ztmp_destructor
-
-    for f in $tmpfiles; do
-        rm -f "$f"
-    done
-    for d in $tmpdirs; do
-        [[ $d == "" || ! -d $d ]] && continue
-        pushd $d
-        [[ `pwd` == "/" ]] && {popd; continue}
-        popd
-        rm -rf "$d"
-    done
-
-    tmpfiles=()
-    tmpdirs=()
-}
-
-arrs+=(tmpfiles)
-arrs+=(tmpdirs)
-destruens+=(_ztmp_destructor)
-
-# }}} Tempfiles
-
 # {{{ Parse commandline options
 
 # for example usage, see Tomb http://tomb.dyne.org
@@ -518,11 +467,6 @@ function helper.isfound isfound() {
     return $?
 }
 
-# faster substitute for cat
-function helper.printfile printfile() {
-    print ${mapfile[$1]}
-}
-
 # }}} Helpers
 
 vars+=(files numfiles dirs)
@@ -532,6 +476,8 @@ arrs+=(alldirs)
 
 maps+=(video audio code text image other web slide sheet archiv)
 maps+=(totals)
+
+vars+=(file_info_date file_info_size dir_info_date dir_info_size)
 
 case `uname` in
   Darwin)
@@ -574,54 +520,87 @@ config_section_type=${config_section_type:-org-mode}
 option_subcommands[__empty]=""
 option_subcommands[__unknown]=""
 
-
-
 func "Zuper $zuper_version initialized"
 func "${#vars} global variables registered"
 func "${#arrs} global arrays registered"
 func "${#maps} global maps registered"
 
+################
+## END OF ZUPER
+## BEGIN HARVEST
+################
+
+LOCAL_ARCH=`uname -s`
+
+function get-file-info() {
+	local ls
+	case ${LOCAL_ARCH:l} in
+		linux)
+			ls=`ls -l --time-style '+%Y-%m-%d' "$1" | tr -s ' '`
+			;;
+		freebsd|darwin)
+			ls=`ls -l -D '%Y-%m-%d' "$1" | tr -s ' '`
+			;;
+	esac
+	print - "$ls" | cut -d ' ' -f 6 | read file_info_date
+	print - "$ls" | cut -d ' ' -f 5 | read file_info_size
+}
+
+function get-dir-info() {
+	local ls
+	case ${LOCAL_ARCH:l} in
+		linux)
+			ls=`ls -d -l --time-style '+%Y-%m-%d' "$1" | tr -s ' '`
+			;;
+		freebsd|darwin)
+			ls=`ls -d -l -D '%Y-%m-%d' "$1" | tr -s ' '`
+			;;
+	esac
+	print - "$ls" | cut -d ' ' -f 6 | read dir_info_date
+#	print - "$ls" | cut -d ' ' -f 5 | read file_info_size
+}
+
 function file-extension-parser() {
    ext=${1##*.}
    case ${ext:l} in
 	   7z|a|apk|ar|bz2|cab|cpio|deb|dmg|egg|gz|iso|jar|lha|mar|pak|pea|rar|rpm|s7z|shar|tar|tbz2|tgz|tlz|war|whl|xpi|xz|zip|zipx)
-		   echo "archive"
+		   print - "archive"
 		   ;;
 	   aac|aiff|ape|au|flac|gsm|it|m3u|m4a|mid|mod|mp3|mpa|pls|ra|s3m|sid|wav|wma|xm)
-		   echo "audio"
+		   print - "audio"
 		   ;;
 	   azw|azw1|azw3|azw4|azw6|cbr|cbz|epub|mobi)
-		   echo "book"
+		   print - "book"
 		   ;;
 	   1.ada|2.ada|ada|adb|ads|asm|asp|aspx|bas|c|c++|cbl|cc|class|clj|cob|cpp|cs|cxx|d|diff|e|el|f|f77|f90|for|fth|ftn|go|groovy|h|hh|hpp|hs|htm|html|hxx|inc|java|js|jsp|jsx|kt|lhs|lisp|lua|m|m4|nim|patch|php|php3|php4|php5|phtml|pl|po|pp|py|r|rb|rs|s|scala|swg|swift|v|vb|vcxproj|xcodeproj|xml)
-																												   echo "code"
+																												   print - "code"
 																												   ;;
 																												   bash|bat|bin|command|crx|csh|exe|fish|ksh|msi|sh|zsh)
-																													   echo "exec"
+																													   print - "exec"
 																													   ;;
 																												   eot|otf|ttf|woff|woff2)
-																													   echo "font"
+																													   print - "font"
 																													   ;;
 																												   3dm|3ds|ai|bmp|dds|dwg|dxf|eps|gif|gpx|jpeg|jpg|kml|kmz|max|png|ps|psd|svg|tga|thm|tif|tiff|webp|xcf)
-																													   echo "image"
+																													   print - "image"
 																													   ;;
 																												   csv|ics|ods|vcf|xls|xlsx)
-																													   echo "sheet"
+																													   print - "sheet"
 																													   ;;
 																												   odp|ppt)
-																													   echo "slide"
+																													   print - "slide"
 																													   ;;
 																												   doc|docx|ebook|log|md|msg|odt|org|pages|pdf|rst|rtf|tex|txt|wpd|wps)
-																													   echo "text"
+																													   print - "text"
 																													   ;;
 																												   3g2|3gp|aaf|asf|avchd|avi|drc|flv|m2v|m4p|m4v|mkv|mng|mov|mp2|mp4|mpe|mpeg|mpg|mpv|mxf|nsv|ogg|ogm|ogv|qt|rm|rmvb|roq|srt|svi|vob|webm|wmv|yuv)
-																													   echo "video"
+																													   print - "video"
 																													   ;;
 																												   css|less|scss|wasm)
-																													   echo "web"
+																													   print - "web"
 																													   ;;
 																												   *)
-																													   echo "other"
+																													   print - "other"
 																													   ;;
 	   esac
 }
@@ -643,7 +622,7 @@ slide_factor=2
 sheet_factor=3
 archiv_factor=10
 
-notice "Harvest $harvest_version - a tool to classify large collections of files and directories"
+notice "Harvest $harvest_version - manage large collections of files and directories"
 
 # counts all totals using a basic fuzzy logic algo and prints results
 fuzzycount() {
@@ -702,101 +681,56 @@ fuzzycount() {
             (( ${totals[$t]} > ${totals[$o]} )) && (( count++ ))
         done
         (( $count == $match )) && {
-			# get the year and print out directories here 
-			year=`stat ${=STAT_OPTS} $arg | cut -d'-' -f1`
-			print "dir,$t,$year,$arg"
+			# get the year and print out directories here
+			get-dir-info "$arg"
+			print - "dir,$t,$dir_info_date,$arg"
 			return 0 }
     done
-	year=`stat ${=STAT_OPTS} $arg | cut -d'-' -f1`
-	print "dir,other,$year,$arg"
+	get-file-info "$arg"
+	print - "dir,other,$dir_info_date,$arg"
     return 0
 }
 
 analyse_files() {
-	act "analysing files "
+	act "analysing files..."
 	prev=""
 	numfiles=0
-	for i in ${(f)1}; do
+	for i in ${(f)"$(find "$1" -maxdepth 1 -type f | tail -n +2)"}; do
+		file_path="$i"
 		[[ -r "$i" ]] || continue
-		mime=`file-extension-parser $i`
-		year=`stat ${=STAT_OPTS} $i | cut -d'-' -f1`
-		files+="file,$mime,$year,$i\n"
-		(print -n "." 1>&2)
+		file-extension-parser "$file_path" | read file_type
+		get-file-info "$file_path"
+		files+="file,$file_type,$file_info_date,$file_path,$file_info_size\n"
 		numfiles=$(( $numfiles + 1 ))
 	done
+	print - "$files"
 }
+
 analyse_dirs() {
 	prev=""
+	realpath "$2" | read base
 	for i in ${(f)1}; do
-
-		mime=`file-extension-parser $i`
-		base=$2
-		func "$mime \t $base"
-
+		file_path="$i"
+		file-extension-parser "$file_path" | read file_type
+		# func "$file_type \t $base"
 		[[ "$base" = "" ]] && continue;
-
-		case "$mime" in
-
+		case "$file_type" in
 			video) (( ++video[$base] )) ;;
-
 			audio) (( ++audio[$base] )) ;;
-
 			image) (( ++image[$base] )) ;;
-
 			code)  (( ++code[$base] ))  ;;
-
 			text)  (( ++text[$base] ))  ;;
-
 			slide)  (( ++slide[$base] ))  ;;
-
 			web)  (( ++web[$base] ))  ;;
-
 			sheet)  (( ++sheet[$base] ))  ;;
-
 			archiv)  (( ++archiv[$base] ))  ;;
-
 			*)     (( ++other[$base] ))
 				   # func "${(r:5:)other[$base]} other :: $base"
 				   ;;
-
 		esac
-
 		[[ "$prev" = "$base" ]] || {
-			(print -n "." 1>&2)
 			prev="$base" }
 		alldirs+=($base)
-	done
-}
-
-cache_check() {
-	[[ -r $cache ]] || {
-		error "cache is empty: $cache"
-		return 1 }
-	return 0
-}
-
-root_check() {
-    root=`grep -m 1 '^#+root:' $cache | cut -d: -f2 | trim`
-	[[ -d $root ]] || {
-		error "no root found in cache"
-		return 1 }
-	return 0
-}
-
-## lists only cached items that actually exist
-cache_list() {
-	needle="$1"
-	for i in ${(f)"$(cat $cache)"}; do
-		[[ "${i[1]}" = "#" ]] && continue
-		fname=${i[(ws:,:)4]}
-		[[ -r "$fname" ]] || continue
-		[[ "$needle" == "" ]] && { print $i; continue }
-		fstype=${i[(ws:,:)1]}
-		genre=${i[(ws:,:)2]}
-		year=${i[(ws:,:)3]}
-		[[ "$fstype" = "$needle" ]] && print "$i"
-		[[ "$genre" = "$needle" ]] && print "$i"
-		[[ "$year" = "$needle" ]] && print "$i"
 	done
 }
 
@@ -817,173 +751,138 @@ getattr() {
 }
 
 # main argument: harvest will parse all filenames found in incoming
-incoming="${1:-`pwd`}"
-cache=$HOME/.cache/harvest
+if [[ -d "$1" ]]; then
+	command='scan'
+else
+	command="${1}"
+	shift 1
+fi
+
 bmarks=$HOME/.config/gtk-3.0/bookmarks
 
-# TODO: build proper argument parsing and useful options
-#       -e to exclude path string patterns from analysis
-
-if   [[ "$incoming" = "source" ]]; then
-    act "internal functions loaded"
-    zuper.exit; return 0
-
-elif [[ -d "$incoming" ]]; then
-	# [[ ${incoming[0]} == "/" ]] || {
-	# 	pushd "$incoming"; incoming=`pwd`; popd }
-    incoming=${incoming}/
-	depth=${2:-2}
-    act   "scanning directory: $incoming (depth $depth)"
-	analyse_files "`find $incoming -maxdepth 1 -type f | tail -n +2`"
-	print
-	[[ "files" == "$2" ]] || {
-		act "analysing directories "
-		for d in ${(f)"$(find $incoming -maxdepth 1 -type d | tail -n +2)"}; do
+case "${command:l}" in
+	scan)
+		target="${1:-$PWD}/"
+		depth="${2:-2}"
+		act   "scanning folder: $target (depth $depth)"
+		analyse_files "$target"
+		act "scanning sub-folders..."
+		for d in ${(f)"$(find $target -maxdepth 1 -type d | tail -n +2)"}; do
 			# TODO: make depth configurable
 			analyse_dirs "`find $d -maxdepth $depth`" $d
 		done
-		print
-	}
-	mkdir -p $HOME/.cache
-	rm -f $cache
-	print "#+root: $incoming" > $cache
-	print "#+depth: $depth"  >> $cache
-	print "${files}" | /usr/bin/tee -a $cache
-	[[ "files" == "$2" ]] || {
 		for o in $alldirs; do
-			fuzzycount "$o"  | /usr/bin/tee -a $cache
+			fuzzycount "$o"
 		done
-	}
-	notice "${numfiles} files and ${#alldirs} directories analysed in total"
-	act   "results saved, use 'harvest ls' to replay on stdout"
+		notice "${numfiles} files and ${#alldirs} folders scanned in `basename $target`"
+		;;
 
-
-elif [[ "$incoming" == "mv" ]]; then
-	needle="$2"
-	dest="$3"
-	moved=0
-	[[ "$dest" = "" ]] && {
-		error "missing argument: destination folder"
-		act "usage: $0 mv type destination/"
-		zuper.exit; return 1 }
-	[[ -d "$dest" ]] || {
-		error "destination is not a folder: $dest"
-		act "usage: $0 mv type destination/"
-		zuper.exit; return 1 }
-	cache_check || { zuper.exit; return 1 }
-	act "Moving harvested files to folder: $dest"
-	[[ "$needle" = "all" ]] && needle=""
-	for i in ${(f)"$(cache_list $needle)"}; do
-		fname=${i[(ws:,:)4]}
-		func "mv $fname $dest/"
-		# this is the only place where harvest modifies the filesystem
-		mv $fname $dest/
-		moved=$(( $moved + 1 ))
-	done
-	act "Done moving $moved items."
-	zuper.exit; return 0
-
-elif [[ "$incoming" == "ls" ]]; then
-	cache_check || { zuper.exit; return 1 }
-	act "Listing harvested files $2"
-	cache_list $2
-	zuper.exit; return 0
-
-# using attr (getfattr / setfattr)
-elif [[ "$incoming" == "attr" ]]; then
-	if command -v setfattr; then
-        cache_check || { zuper.exit; return 1 }
-        act "Set tags as filesystem extended attributes"
-        act "using harvest.type key/value store"
-        root=`grep -m 1 '^#+root:' $cache | cut -d: -f2 | trim`
-        pushd $root
-        for i in ${(f)"$(cache_list $2)"}; do
-            fname=${i[(ws:,:)4]}
-            ftype=${i[(ws:,:)2]}
-            fyear=${i[(ws:,:)3]}
-            setfattr -n "harvest.type" -v "$ftype" "$fname"
-            setfattr -n "harvest.year" -v "$fyear" "$fname"
-        done
-        popd; zuper.exit; return 0
-    else
-		error "attr commands not found (setfattr)"
-	fi
-
-# using tmsu
-elif [[ "$incoming" == "tmsu" ]]; then
-	command -v tmsu >/dev/null || {
-		error "tmsu command not found"
-		zuper.exit; return 1 }
-    cache_check || { zuper.exit; return 1 }
-    act "Tagging harvested files with tmsu"
-    root=`grep -m 1 '^#+root:' $cache | cut -d: -f2 | trim`
-    pushd $root
-    func "tmsu init -v -D $root"
-    tmsu init -v -D $root
-    tmsu config \
-         autoCreateTags=yes \
-         autoCreateValues=no \
-         directoryFingerprintAlgorithm=none \
-         fileFingerprintAlgorithm=none \
-         reportDuplicates=yes
-
-    for i in ${(f)"$(cache_list $2)"}; do
-        fname=${i[(ws:,:)4]}
-        [[ -r "$fname" ]] || continue
-        ftype=${i[(ws:,:)2]}
-        fyear=${i[(ws:,:)3]}
-        # act "tmsu tag $fname $ftype"
-        tmsu tag "$fname" "$ftype"
-        numfiles=$(( $numfiles + 1 ))
-    done
-    popd
-    zuper.exit; return 0
-
-elif [[ "$incoming" == "mount" ]]; then
-	command -v tmsu >/dev/null || {
-		error "tmsu command not found"
-		zuper.exit; return 1 }
-	cache_check || { zuper.exit; return 1 }
-	root_check  || { zuper.exit; return 1 }
-	[[ -r $root/.tmsu/db ]] || {
-		error "tmsu tags not initialised, use 'harvest tmsu'"
-		zuper.exit; return 1 }
-	[[ -d $root/.mnt/tags ]] || {
-		act "Mounting tagged filesystem in $root/.mnt"
-		mkdir -p $root/.mnt
-		tmsu mount -D $root/.tmsu/db $root/.mnt || {
-			error "Error mounting tagged filesystem using tmsu"
-			zuper.exit; return 1 }
-	}
-	# setup gtk bookmarks too (for sidebar in pcmanfm, thunar etc.)
-	[[ -r $bmarks~harvest ]] || {
-		mv $bmarks $bmarks~harvest
-		for i in ${(f)"$(ls $root/.mnt/tags)"}; do
-			print "file://$root/.mnt/tags/$i" >> $bmarks
+	ls)
+		needle="$1"
+		listed=0
+		act "List existing harvested files of type: $needle"
+		for i in ${(f)"$(cat)"}; do
+			[[ "$needle" = "all" ]] || [[ "${i[(ws:,:)2]}" = "$needle" ]] && {
+				fname="${i[(ws:,:)4]}"
+				[[ -r "$fname" ]] && {
+					ls "$fname"
+					listed=$(( $listed + 1 ))
+				}
+			}
 		done
-	}
-	act "$root tagged filesytem ready (path in clipboard and \$harvest)"
-	print $root/.mnt | xclip
-	export harvest=$root/.mnt
+		act "Done listing $listed items."
+		;;
 
-elif [[ "$incoming" == "umount" ]]; then
-	command -v tmsu >/dev/null || {
-		error "tmsu command not found"
-		zuper.exit; return 1 }
-	for i in ${(f)"$(mount | awk '
-/fuse.pathfs.pathInode/ { print $3 }')"}; do
-		act "umount $i"
-		tmsu umount $i
-		if [[ $? = 0 ]]; then
-			act "$i tagged filesystem unmounted"
+	# using attr (getfattr / setfattr)
+	attr)
+		if command -v setfattr >/dev/null; then
+			act "Set harvest.type extended attribute on harvested files from stdin"
+			for i in ${(f)"$(cat)"}; do
+				fname=${i[(ws:,:)4]}
+				ftype=${i[(ws:,:)2]}
+				[[ -r "$fname" ]] && {
+					setfattr -n "harvest.type" -v "$ftype" "$fname"
+				}
+			done
 		else
-			error "$i error unmounting tagged filesystem"
-			break
+			error "setfattr not found"
 		fi
-	done
-	[[ -r $bmarks~harvest ]] &&
-		mv $bmarks~harvest $bmarks
-	unset harvest
-fi
+		;;
+
+	tmsu)
+		command -v tmsu >/dev/null || {
+			error "TMSU not installed"
+			zuper.exit; return 1
+		}
+		root="${1:-$PWD}"
+		act "tagging with tmsu: $root"
+		func "tmsu init -v -D $root"
+		tmsu init -v -D $root
+		tmsu config \
+			 autoCreateTags=yes \
+			 autoCreateValues=no \
+			 directoryFingerprintAlgorithm=none \
+			 fileFingerprintAlgorithm=none \
+			 reportDuplicates=yes
+		for i in ${(f)"$(cat)"}; do
+			fname=${i[(ws:,:)4]}
+			[[ -r "$fname" ]] || continue
+			ftype=${i[(ws:,:)2]}
+			fyear=${i[(ws:,:)3]}
+			# act "tmsu tag $fname $ftype"
+			tmsu tag "$fname" "$ftype"
+			numfiles=$(( $numfiles + 1 ))
+		done
+		notice "Files tagged in TMSU: $numfiles"
+		;;
+
+	mount)
+		command -v tmsu >/dev/null || {
+			error "TMSU not installed"
+			zuper.exit; return 1
+		}
+		root="${1:-$PWD}"
+		act "Mounting TMSU in: $root"
+		[[ -r $root/.tmsu/db ]] || {
+			error "tmsu tags not initialised, use 'harvest tmsu'"
+			zuper.exit; return 1 }
+		[[ -d $root/.mnt/tags ]] || {
+			act "Mounting tagged filesystem in $root/.mnt"
+			mkdir -p $root/.mnt
+			tmsu mount -D $root/.tmsu/db $root/.mnt || {
+				error "Error mounting tagged filesystem using tmsu"
+				zuper.exit; return 1 }
+		}
+		# setup gtk bookmarks too (for sidebar in pcmanfm, thunar etc.)
+		[[ -r $bmarks~harvest ]] || {
+			mv $bmarks $bmarks~harvest
+			for i in ${(f)"$(ls $root/.mnt/tags)"}; do
+				print "file://$root/.mnt/tags/$i" >> $bmarks
+			done
+		}
+		act "$root tagged filesytem ready: $root"
+		print - "$root/.mnt"
+		;;
+
+	umount|unmount)
+		command -v tmsu >/dev/null || {
+			error "tmsu command not found"
+			zuper.exit; return 1 }
+		for i in ${(f)"$(mount | awk '
+/fuse.pathfs.pathInode/ { print $3 }')"}; do
+			act "umount $i"
+			tmsu umount "$i"
+			if [[ $? = 0 ]]; then
+				act "$i tagged filesystem unmounted"
+				[[ -r $bmarks~harvest ]] &&
+					mv $bmarks~harvest $bmarks
+				unset harvest
+			else
+				error "$i error unmounting tagged filesystem"
+				break
+			fi
+		done
+		;;
+esac
 
 zuper.exit; return 0
